apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
  namespace: default
spec:
  parallelism: 5    # Run 5 pods in parallel
  completions: 5    # Require 5 successful completions
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 192.168.5.169:5000/consumer:v0.4
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: PRODUCER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ML_INFERENCE_SERVICE
          value: "ml-server:80"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
        - name: SESSION_TIMEOUT_MS
          value: "30000"  # 30 seconds
        - name: HEARTBEAT_INTERVAL_MS
          value: "10000"  # 10 seconds
      restartPolicy: Never
