apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 192.168.5.169:5000/consumer:v0.2
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
      restartPolicy: Never