apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 192.168.5.169:5000/consumer:v0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: ML_INFERENCE_SERVICE
          value: "ml-server:80"
        - name: DATABASE_SERVICE
          value: "mongo:27017"
        - name: SESSION_TIMEOUT_MS
          value: "30000"  # 30 seconds
        - name: HEARTBEAT_INTERVAL_MS
          value: "10000"  # 10 seconds
      restartPolicy: Never
