apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 192.168.1.15:5000/consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: ML_INFERENCE_SERVICE
          value: "ml-inference-service:80"
        - name: DATABASE_SERVICE
          value: "mongo:27017"
      restartPolicy: Never
