apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kafka.yaml
  - mongo.yaml
  - consumer-job.yaml
  - ml-inference-service.yaml
  - producer-job.yaml

# (Optional) Configuration customization
# You can add other configurations such as patches, config maps, and secrets here
# patchesStrategicMerge:
#   - some-patch.yaml

# (Optional) Namespace to apply all resources to
# namespace: my-namespace

# (Optional) Image overrides
# images:
#   - name: your-image
#     newName: localhost:5000/your-image
#     newTag: latest

# Add any other customization you need below.
