---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-server
  template:
    metadata:
      labels:
        app: ml-server
    spec:
      containers:
        - name: ml-server
          image: 192.168.5.169:5000/ml-server:v0.1  # Pulls from local v0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "2000m"
            requests:
              memory: "1000Mi"
              cpu: "750m"
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: MONGO_URI
              value: "mongodb://admin:password@mongodb:27017"
            - name: CUDA_VISIBLE_DEVICES
              value: "-1"  # Disable GPU
---
apiVersion: v1
kind: Service
metadata:
  name: ml-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ml-server
