---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-server
  template:
    metadata:
      labels:
        app: ml-server
    spec:
      containers:
        - name: ml-server
          image: 192.168.1.15:5000/ml-server:latest  # Pulls from local registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: MONGO_URI
              value: "mongodb://admin:password@mongodb:27017"

---
apiVersion: v1
kind: Service
metadata:
  name: ml-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ml-server
