apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: 192.168.5.169:5000/producer:v0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: PRODUCER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
