apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job-p4
  namespace: default
spec:
  parallelism: 5    # Run 5 pods in parallel
  completions: 5    # Require 5 successful completions
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: 192.168.5.169:5000/producer:v0.2
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: PRODUCER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
