apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-stream-coordinator
  labels:
    app: spark-stream-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-stream-coordinator
  template:
    metadata:
      labels:
        app: spark-stream-coordinator
    spec:
      containers:
      - name: spark-container
        image: my-spark-image:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        ports:
        - containerPort: 7077
