---
- name: "Install libraries Kubernetes needs"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes  # Update the cache before installing these packages

- name: "Download Google Cloud public signing key"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    # Instead of the old apt-key method, we will use signed-by option in the sources list

- name: "Add Kubernetes apt repository for Ubuntu 22.04 (Jammy)"
  copy:
    content: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-jammy main
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: "Update apt package index after adding Kubernetes repo"
  apt:
    update_cache: yes
    cache_valid_time: 3600  # Optional: Cache validity in seconds

- name: "Install Kubernetes libraries"
  apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

- name: "Hold Kubernetes packages at current version"
  apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        force: yes
        allow_downgrade: yes
        allow_unauthenticated: yes
        autoremove: no
        only_upgrade: no
        upgrade: no
        hold: yes

- name: "Disable swap"
  command: swapoff -a
  when: ansible_virtualization_type != "docker"

- name: "Ensure swap is disabled on reboot"
  replace:
        path: /etc/fstab
        regexp: '^\s*([^#\s]+\s+)+swap\s+'
        replace: '#\1swap'

- name: "Enable and start kubelet service"
  systemd:
        name: kubelet
        enabled: yes
        state: started