---
- name: "Update apt repository cache"
  apt:
    update_cache: yes

- name: "Install required apt packages"
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: yes
