---

# ################################################################
# ### Play 1: check if required variables are defined or not.
# #           If not defined then simply exit the entire play
# #
# ################################################################
# - name: "Check if required variables that drive the deployment are defined"
#   hosts: LocalMC   # this alias is specified in the inventory file
#   remote_user:  "{{ local_user }}"  # since the play executes on LocalMC,
#                                     # we use the local user
#   gather_facts: no
#   collections:    # collections is like import the necessary Ansible
#                   # galaxy packages needed for the play to execute
#   - ansible-base

#   tasks:
#   # @@ You have to write the following child playbook @@
#   - import_tasks: tasks/playbook_check_variables.yaml


# #####################################################
# ### Play 2: Create VMs on the Cloud
# #
# #####################################################
# - name: "Play 2: Create VMs on Chameleon"
#   hosts: LocalMC   # this alias is specified in the Inventory file
#   remote_user:  "{{ local_user }}" 
#   gather_facts: no 
#   become: false    # No need for sudo as we are not installing anything
#   collections:
#   - ansible-base
#   - openstack.cloud.collection
  
#   tasks:    # the task to be performed
#   # @@ You have to write the following child playbook @@
#   - import_tasks: tasks/playbook_create_vms.yaml

  #####################################################
### Play 3: Get facts from Cloud VM
#
# In this play, you must retrieve various facts of the
# VMs you have created. The most important are their
# private IP addresses that you will need in subsequent
# plays
#####################################################
- name: "Play 3: Perform fact gathering on all Cloud VMs"
  hosts: LocalMC  # specified in the Inventory file
  remote_user:  "{{ local_user }}"

  gather_facts: no
  become: false
  collections:
  - ansible-base
  - openstack.cloud.collection

  tasks:    # the task to be performed
  # @@ You have to write the following child playbook @@
  - import_tasks: tasks/playbook_retrieve_facts_vms.yaml
