---
- name: "Ensure pip is installed"
  apt:
    name: python3-pip
    state: present

- name: "Install required Python packages via pip"
  pip:
    name:
      - kafka-python
      - requests
      - flask
