#!/usr/bin/env bash
export OS_AUTH_URL=https://kvm.tacc.chameleoncloud.org:5000/v3
export OS_IDENTITY_API_VERSION=3
export OS_TOKEN=None
export OS_AUTH_TOKEN=None
export OS_PROJECT_ID=9c3848cc69044cdfb5a8c7b5e273b276
export OS_REGION=KVM@TACC
export OS_AUTH_TYPE=token
