apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-tester
  template:
    metadata:
      labels:
        app: load-tester
    spec:
      containers:
      - name: load-tester
        image: localhost:5000/load-tester:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
            memory: "2280Mi"
          limits:
            cpu: "500m"
            memory: "2560Mi"
