apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester
spec:
  replicas: 5 # each replica does 1000 requests x 100 workers then completes (~50 requests/s in Kind)
  selector:
    matchLabels:
      app: load-tester
  template:
    metadata:
      labels:
        app: load-tester
    spec:
      containers:
      - name: load-tester
        image: localhost:5000/load-tester:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1000m"
            memory: "2280Mi"
          limits:
            cpu: "2000m"
            memory: "2560Mi"
