apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-resource-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: high-resource-app
  template:
    metadata:
      labels:
        app: high-resource-app
    spec:
      containers:
      - name: high-resource-app
        image: localhost:5000/high-resource-app:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
