apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-server
  template:
    metadata:
      labels:
        app: ml-server
    spec:
      containers:
      - name: ml-server
        image: 192.168.5.169:5000/ml-server:v0.1
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
