# consumer-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: consumer-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: team5a/consumer:latest  # Replace with your actual image name
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: ML_INFERENCE_SERVICE
          value: "ml-inference-service:80"
        - name: DATABASE_SERVICE
          value: "database-service:5432"
      restartPolicy: Never
