# producer-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job
  namespace: default  # Using 'default' unless your team is using a different namespace
spec:
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: team5a/producer:latest  # Replace with your actual image name
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"  # Expected Kafka service name and port
        - name: PRODUCER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
