---
# Apply to master and workers
- hosts: CloudVMs
  remote_user: "{{ cloud_user }}" # since this play operates on the cloud
                                  # VMs, the user on those VMs is the
                                  # cloud_user variable
  become: yes
  tasks:
    - name: Enable IPv4 for Kubernetes
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.ipv4.ip_forward = 1
        EOF
# - hosts: master
#   remote_user: "{{ cloud_user }}" # since this play operates on the cloud
#                                   # VMs, the user on those VMs is the
#                                   # cloud_user variable
#   become: true
#   tasks:
    # - name: Initialize Kubernetes master
    #   command: kubeadm init --pod-network-cidr=10.244.0.0/16
    #   register: kubeadm_output
    #   ignore_errors: yes

    # - name: Set up kubectl for the current user
    #   command: "{{ item }}"
    #   with_items:
    #     - "mkdir -p $HOME/.kube"
    #     - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
    #     - "chown $(id -u):$(id -g) $HOME/.kube/config"

    # - name: Install Calico network plugin
    #   command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    #   # when: "'calico' in kubeadm_output.stdout"

# - hosts: workers
#   remote_user: "{{ cloud_user }}" # since this play operates on the cloud
#                                   # VMs, the user on those VMs is the
#                                   # cloud_user variable
#   become: true
#   tasks:
#     - name: Join worker nodes to the cluster
#       command: "{{ hostvars['master']['kubeadm_output']['stdout_lines'][0] }}"
#       when: "'kubeadm join' in hostvars['master']['kubeadm_output']['stdout']"
