# Use an official Golang runtime as a parent image
FROM golang:1.22.6 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
#COPY go.mod go.sum ./
COPY go.mod ./

# Download dependencies
# RUN go mod download

# Copy the source code
COPY *.go ./

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o http-app

# Use a minimal base image for the final container
FROM alpine:3.18

# Set the working directory inside the container
WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/http-app .

# Expose the app's port
EXPOSE 8080

# Set the command to run the app
CMD ["./http-app"]