apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 70
  # - type: External
  #   external:
  #     metricName: request_queue_length
  #     target:
  #       type: Value
  #       value: "50"
  # - type: External
  #   external:
  #     metricName: avg_response_time
  #     target:
  #       type: Value
  #       value: "200ms"
