apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: http-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: http-app
  updatePolicy:
    updateMode: "Auto"  # Options: 'Off', 'Initial', 'Auto'
  # Set the historySamples to change the observation window
  observationWindow: 2m # Number of data points to observe - 
